# Generated by Django 3.1 on 2023-04-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230413_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product',
            new_name='product_name',
        ),
    ]
