# Generated by Django 3.1 on 2023-05-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
    ]
