# Generated by Django 3.1 on 2023-04-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
    ]
